spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: admin

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

logging:
  level:
    com.cgi.api: DEBUG

jwt:
  secret: fhsjwHWjhwqLxTgpV+nBMpM3XB0jgETR0vWsyRFV9oQ=
  expirationMs: 43200000 # 12 hours
  refreshExpirationMs: 86400000 # 1 day

tmdb:
  api:
    key: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiMjE3OTJhOTAyZTFiNmY4OTA5MzI5ZjZiOGFlNTA5ZiIsInN1YiI6IjY1Zjg0MjFjZDhmNDRlMDE3YzUyNjRkNyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.SVxN_HsOqtM3iKVn0ABlIuFKn_X9VrYjUWIJpax2ffM
#  key: b21792a902e1b6f8909329f6b8ae509f
