spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: admin

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

jwt:
  secret:
    key: fhsjwHWjhwqLxTgpV+nBMpM3XB0jgETR0vWsyRFV9oQ=
  expiration: 43200000
